In [1]:
import pandas as pd

In [2]:
# create a dataframe of cities and weather data
india_weather = pd.DataFrame({'city':['Mumbai','Delhi','Bangalore'],
                  'temperature':[32,45,30],
                  'humidity':[80,60,78]})
india_weather

        city  temperature  humidity
0     Mumbai           32        80
1      Delhi           45        60
2  Bangalore           30        78

In [3]:
usa_weather = pd.DataFrame({'city':['Newyork','Chicago','Orlando'],
                  'temperature':[21,14,35],
                  'humidity':[68,65,75]})
usa_weather

      city  temperature  humidity
0  Newyork           21        68
1  Chicago           14        65
2  Orlando           35        75

In [4]:
# How to concat 2 dataframes
df = pd.concat([india_weather,usa_weather]) #this creates a df with individual indices taken from the dataframes
df

        city  temperature  humidity
0     Mumbai           32        80
1      Delhi           45        60
2  Bangalore           30        78
0    Newyork           21        68
1    Chicago           14        65
2    Orlando           35        75

In [5]:
df = pd.concat([india_weather,usa_weather],ignore_index=True) #this creates a df with continous indices
df

        city  temperature  humidity
0     Mumbai           32        80
1      Delhi           45        60
2  Bangalore           30        78
3    Newyork           21        68
4    Chicago           14        65
5    Orlando           35        75

In [6]:
df = pd.concat([india_weather,usa_weather],keys=['india','usa'],ignore_index=False) #this creates a df with additional indices of choice using keys argument
df

              city  temperature  humidity
india 0     Mumbai           32        80
      1      Delhi           45        60
      2  Bangalore           30        78
usa   0    Newyork           21        68
      1    Chicago           14        65
      2    Orlando           35        75

In [7]:
# the advantage of using keys is we can sort out the data based on keys as below using df.loc
df.loc['india']

        city  temperature  humidity
0     Mumbai           32        80
1      Delhi           45        60
2  Bangalore           30        78

In [8]:
# Create a dataframe of temperature data
temperature_df = pd.DataFrame({'city':['mumbai','delhi','bangalore'],
                              'temperature':[32,45,30]},index=[0,1,2])
temperature_df

        city  temperature
0     mumbai           32
1      delhi           45
2  bangalore           30

In [9]:
# Create a dataframe of windspeed data
windspeed_df = pd.DataFrame({'city':['delhi','mumbai'],
                              'windspeed':[12,15]},index=[1,0])
windspeed_df

     city  windspeed
1   delhi         12
0  mumbai         15

In [10]:
# How to combine the temperature and windspeed df's to a single df so that the columns appear side by side
# if we use the pd.concat it won't work, the common rows will not be combined
df_concat = pd.concat([temperature_df,windspeed_df])
df_concat

        city  temperature  windspeed
0     mumbai         32.0        NaN
1      delhi         45.0        NaN
2  bangalore         30.0        NaN
1      delhi          NaN       12.0
0     mumbai          NaN       15.0

In [11]:
# if we use axis = 1
df_concat_1 = pd.concat([temperature_df,windspeed_df],axis=1)
df_concat_1
# The combined df does not appear correct since the temperature and wind speed of delhi and mumbai are mismatched
# Use index argument in the individual dataframes to correct this

        city  temperature    city  windspeed
0     mumbai           32  mumbai       15.0
1      delhi           45   delhi       12.0
2  bangalore           30     NaN        NaN

In [12]:
# How to combine a series to a dataframe
# Lets create a series for events of the cities
event_Series = pd.Series(['Humid','Dry','Rain'],name="event")
event_Series

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [13]:
df_temp=pd.concat([temperature_df,event_Series],axis=1)
df_temp

        city  temperature  event
0     mumbai           32  Humid
1      delhi           45    Dry
2  bangalore           30   Rain