In [11]:
import pandas as pd

### Operations on csv files

In [16]:
# how to read a csv file with an extra row at the top which is not needed
df = pd.read_csv('stock_data.csv',header=1) # or
# df = pd.read_csv('stock_data.csv',skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65            n.a
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [13]:
# how to read a csv file without actual headers or column names missing
df_copy=pd.read_csv('stock_data - Copy.csv',header=None)
df_copy

       0              1    2     3              4
0  GOOGL          27.82   87   845     larry page
1    WMT           4.61  484    65            n.a
2   MSFT             -1   85    64     bill gates
3    RIL  not available   50  1023  mukesh ambani
4   TATA            5.6   -1  n.a.     ratan tata

In [14]:
# If you want to add names to the columns
df_copy2=pd.read_csv('stock_data - Copy.csv',header=None,names=['ticker',"eps","revenue","price","people"])
df_copy2

  ticker            eps  revenue price         people
0  GOOGL          27.82       87   845     larry page
1    WMT           4.61      484    65            n.a
2   MSFT             -1       85    64     bill gates
3    RIL  not available       50  1023  mukesh ambani
4   TATA            5.6       -1  n.a.     ratan tata

In [19]:
# If you want to read only a few rows from a large csv file
df_copy3=pd.read_csv('stock_data.csv',header=1,nrows=3)
df_copy3

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65         n.a
2    MSFT  -1.00       85     64  bill gates

In [23]:
# how to change the not available values in each cell to read as NaN
df_copy3=pd.read_csv('stock_data.csv',header=1,na_values=['not available','n.a','n.a.']) # add all the values which are not available into the list of na_values
df_copy3

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3     RIL    NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [24]:
# how to choose the columns you want and fill the NA values as NaN
df_copy4 = pd.read_csv('stock_data.csv',na_values={
    'eps':['not available','n.a','n.a.'],
    'revenue':['not available','n.a','n.a.',-1],
    'price':['not available','n.a','n.a.']
})
df_copy4

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            n.a
2    MSFT  -1.00     85.0    64.0     bill gates
3     RIL    NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [29]:
# how to write a df to a csv
df_copy4.to_csv("new.csv",index=False)
# how to write specific columns of a df to csv
df_copy4.to_csv("new1.csv",index=False,columns=['tickers','revenue'])
# how to skip headers and write the df to a csv
df_copy4.to_csv("new3.csv",header=False)

### Operations on excel files

In [31]:
# Read an excel file and choose the sheet you want
df_xls = pd.read_excel("stock_data.xlsx","Sheet1")
df_xls

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65            n.a
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [35]:
# How to perform operation on any cell of a column. For example, change the name in people cell for walmart to sam walton
def change_cell(cell):
    if cell=="n.a":
        return "sam walton"
    return cell
df_xls_copy1=pd.read_excel("stock_data.xlsx","Sheet1",converters={
    "people":change_cell
})
df_xls_copy1

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65     sam walton
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
# How to write a df to an excel, skipping the index and starting the sheet from 1,1 cell
df_xls_copy1.to_excel("new_excel.xlsx",sheet_name="stocks",index=False,startrow=1,startcol=1)

In [46]:
# how to export 2 df's to a single excel under 2 sheets
weather_data = {
    'day':['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature':[32,35,28,24,32,31],
    'windspeed':[6,7,2,7,4,2],
    'event':['Rainy','Sunny','Snow','Snow','Rain','Sunny']
    
}
df_weather = pd.DataFrame(weather_data)
df_stocks = pd.DataFrame({
    'tickers':['GOOGL','WMT','MSFT'],
    'price':[845,65,64],
    'pe':[30.37,14.23,30.97],
    'eps':[27.82,4.61,2.12]
})
with pd.ExcelWriter('stocks_weather.xlsx') as writer:
    df_weather.to_excel(writer,sheet_name="weather"),
    df_stocks.to_excel(writer,sheet_name="stocks")