In [1]:
import pandas as pd

In [2]:
# create a dataframe of temperature across cities of usa
df1 = pd.DataFrame({'city':['NewYork','Chicago','Orlando'],
                   'temperature':[21,14,35]})
df1

      city  temperature
0  NewYork           21
1  Chicago           14
2  Orlando           35

In [3]:
# create a dataframe of humidity across cities of usa
df2 = pd.DataFrame({'city':['Chicago','NewYork','Orlando'],
                   'humidity':[65,68,75]})
df2

      city  humidity
0  Chicago        65
1  NewYork        68
2  Orlando        75

In [4]:
# merge the df's using on column method
df_merge = pd.merge(df1,df2,on='city')
df_merge

      city  temperature  humidity
0  NewYork           21        68
1  Chicago           14        65
2  Orlando           35        75

In [5]:
# What if the 2 df's have different cities

In [6]:
df3 = pd.DataFrame({'city':['NewYork','Chicago','Orlando','Baltimore'],
                   'temperature':[21,14,35,32]})
df3
df4 = pd.DataFrame({'city':['Chicago','NewYork','Sanfrancisco'],
                   'humidity':[65,68,72]})
df4

           city  humidity
0       Chicago        65
1       NewYork        68
2  Sanfrancisco        72

In [7]:
df_merge_inner = pd.merge(df3,df4,on='city') # default method for how is inner which is basically intersection of the df's
df_merge_inner
# Notice that only the rows having cities in common have been merged, Orlando, Sanfrancisco and Baltimore are left out

      city  temperature  humidity
0  NewYork           21        68
1  Chicago           14        65

In [8]:
df_merge_outer = pd.merge(df3,df4,on='city',how='outer') # outer method is basically union of the df's
df_merge_outer

           city  temperature  humidity
0     Baltimore         32.0       NaN
1       Chicago         14.0      65.0
2       NewYork         21.0      68.0
3       Orlando         35.0       NaN
4  Sanfrancisco          NaN      72.0

In [9]:
df_merge_left = pd.merge(df3,df4,on='city',how='left') # left method takes all the elements in the left df (first in the order). For entries missing in any df NaN is entered
df_merge_left

        city  temperature  humidity
0    NewYork           21      68.0
1    Chicago           14      65.0
2    Orlando           35       NaN
3  Baltimore           32       NaN

In [10]:
df_merge_right = pd.merge(df3,df4,on='city',how='right') # left method takes all the elements in the right df (second in the order). For entries missing in any df NaN is entered
df_merge_right

           city  temperature  humidity
0       Chicago         14.0        65
1       NewYork         21.0        68
2  Sanfrancisco          NaN        72

In [11]:
#  How to check from which dataframe the entries were merged, use indicator=True
df_merge_outer = pd.merge(df3,df4,on='city',how='outer',indicator=True) # outer method is basically union of the df's
df_merge_outer

           city  temperature  humidity      _merge
0     Baltimore         32.0       NaN   left_only
1       Chicago         14.0      65.0        both
2       NewYork         21.0      68.0        both
3       Orlando         35.0       NaN   left_only
4  Sanfrancisco          NaN      72.0  right_only

In [12]:
# How to use suffixes when the dataframes have common column names
df5 = pd.DataFrame({'city':['new york','chicago','orlando','baltimore'],
                   'temperature':[21,14,35,38],
                   'humidity':[65,68,71,75]})
df5

        city  temperature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [13]:
df6 = pd.DataFrame({'city':['chicago','new york','san diego'],
                   'temperature':[21,14,35],
                   'humidity':[65,68,71]})
df6

        city  temperature  humidity
0    chicago           21        65
1   new york           14        68
2  san diego           35        71

In [14]:
# When merged, notice that an x is added by default to the column names
df_merge_suffix = pd.merge(df5,df6,on='city')
df_merge_suffix

       city  temperature_x  humidity_x  temperature_y  humidity_y
0  new york             21          65             14          68
1   chicago             14          68             21          65

In [15]:
# add suffixes to identify
df_merge_suffix = pd.merge(df5,df6,on='city',suffixes=['_left','_right'])
df_merge_suffix

,city,temperature_left,humidity_left,temperature_right,humidity_right
0,new york,21,65,14,68
1,chicago,14,68,21,65