In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('weather.csv')
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [4]:
# Pivot helps in transposing rows to columns and vis-a-vis
df.pivot(index='date',columns='city') # to create dates as rows and other data are grouped based on city

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

In [5]:
# to create dates as rows and choose only humidity as values
df.pivot(index='date',columns='city',values='humidity')

city      beijing  mumbai  new york
date
5/1/2017       26      80        56
5/2/2017       30      83        58
5/3/2017       35      85        60

In [9]:
# or use temperature as values
df.pivot(index='date',columns='city',values='temperature')

city      beijing  mumbai  new york
date
5/1/2017       80      75        65
5/2/2017       77      78        66
5/3/2017       79      82        68

In [6]:
# make the city as rows
df.pivot(index='city',columns='date',values='temperature')

date      5/1/2017  5/2/2017  5/3/2017
city
beijing         80        77        79
mumbai          75        78        82
new york        65        66        68

### Pivot tables are used to summarize and aggregate data inside dataframe

In [7]:
df_pivotTable=pd.DataFrame({'date':['5/1/2017','5/1/2017','5/2/2017','5/2/2017',
                     '5/1/2017','5/1/2017','5/2/2017','5/2/2017'],
             'city':['new york','new york','new york','new york',
                    'mumbai','mumbai','mumbai','mumbai'],
             'temperature':[65,61,70,72,75,78,82,82],
             'humidity':[56,54,60,62,80,83,85,26]})
df_pivotTable

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           82        26

In [8]:
# How to create a pivot table with average temperature across the cities for both dates
df.pivot_table(index='city',columns='date')

         humidity                   temperature
date     5/1/2017 5/2/2017 5/3/2017    5/1/2017 5/2/2017 5/3/2017
city
beijing      26.0     30.0     35.0        80.0     77.0     79.0
mumbai       80.0     83.0     85.0        75.0     78.0     82.0
new york     56.0     58.0     60.0        65.0     66.0     68.0

### How to use grouper function

In [9]:
df_grouper = pd.DataFrame({'date':['5/1/2017','5/2/2017','5/3/2017',
                                   '12/1/2017','12/2/2017','12/3/2017'],
                          'city':['new york','new york','new york',
                                  'new york','new york','new york'],
                          'temperature':[65,61,70,30,28,25],
                          'humidity':[56,54,60,50,52,51]})
df_grouper

        date      city  temperature  humidity
0   5/1/2017  new york           65        56
1   5/2/2017  new york           61        54
2   5/3/2017  new york           70        60
3  12/1/2017  new york           30        50
4  12/2/2017  new york           28        52
5  12/3/2017  new york           25        51

In [10]:
# convert the date column to date time object instead of string object
df_grouper['date']=pd.to_datetime(df_grouper['date']) # to convert the date object to date time
type(df_grouper['date'][0]) # to check if the object has been converted

pandas._libs.tslibs.timestamps.Timestamp

In [11]:
df_grouper.pivot_table(index=pd.Grouper(freq='ME',key='date'),columns='city')

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667