In [1]:
import pandas as pd

In [2]:
# using dictionaries
weather_data = {
    'day':['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature':[32,35,28,24,32,31],
    'windspeed':[6,7,2,7,4,2],
    'event':['Rainy','Sunny','Snow','Snow','Rain','Sunny']
    
}
df_weather = pd.DataFrame(weather_data)
df_weather

        day  temperature  windspeed  event
0  1/1/2017           32          6  Rainy
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [3]:
# how to fetch head and tails of a df
df_weather.head(5)
df_weather.tail(1)

        day  temperature  windspeed  event
5  1/6/2017           31          2  Sunny

In [4]:
# the shape of the df can be obtained from df.shape which gives a tuple
rows,cols=df_weather.shape
print(f'The rows and columns of the df are {rows} and {cols}')

The rows and columns of the df are 6 and 4

In [5]:
# indexing in pandas
print(df_weather[2:5])
print(df_weather[:3])

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain
        day  temperature  windspeed  event
0  1/1/2017           32          6  Rainy
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [6]:
# how to fetch the column names from a df
df_weather.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [7]:
# print the individual chosen column
print(df_weather['day']) #method 1
print(df_weather.day) #method 2

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object
0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [8]:
# how to check the type of data in a df
type(df_weather['day']) # all columns in a df are called as pandas series

pandas.core.series.Series

In [9]:
# how to output selected columns (more than 1) from a dataframe
df_weather[['day','temperature']]

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

In [10]:
# how to perform some basic operations on the columns of a df
print('Maximum temperature',df_weather['temperature'].max())  #to get the maximum value from the column
print('Average temperature',df_weather.temperature.mean()) # to get the mean or average value
print('Standard deviation',df_weather['temperature'].std())
df_weather.describe() # gives the statistical info for the columns containing numerical data

Maximum temperature 35
Average temperature 30.333333333333332
Standard deviation 3.8297084310253524

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [11]:
# how to perform conditional operations on the columns of interest
df_weather[df_weather['temperature']>=32]  #provide me days where the temperature was >=32
df_weather[df_weather['temperature']==df_weather['temperature'].max()] #give me the days where the temperature was == to the max temperature
df_weather['day'][df_weather['temperature']==df_weather['temperature'].max()] # give me only the day not the entire row where temperature == max
df_weather[['temperature','day']][df_weather['temperature']==df_weather['temperature'].max()] # give me the day and the temperature value in the df where the temperature == max

   temperature       day
1           35  1/2/2017

In [12]:
# how to set index for a df other than the default index
# df_weather.set_index('day',inplace=True)
df_weather

        day  temperature  windspeed  event
0  1/1/2017           32          6  Rainy
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [13]:
# Now the date can be used as index and corresponding rows can be fetched using the loc function
df_weather.loc['1/5/2017']

KeyError: '1/5/2017'

In [ ]:
# If you want the original index, use reset index along with inplace=True
df_weather.reset_index(inplace=True)
df_weather

In [ ]:
# set event as index and fetch rows where it is snow
df_weather.set_index('event',inplace=True)
df_weather.loc['Snow']

In [ ]:
# how to read csv files
df_csv = pd.read_csv('weather_data.csv')
df_csv

In [ ]:
# how to read an excel file
df_xls = pd.read_excel('weather_data.xlsx')
df_xls

In [ ]:
# how to create a dataframe using tuples
weatherdata_tuples = [
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('/1/3/2017',28,2,'Snow')
]
df_tuples = pd.DataFrame(weatherdata_tuples,columns=['day','temperature','windSpeed','event'])
df_tuples

In [ ]:
# how to create a dataframe using dictionary as row entries
weather_data_dict = [
{'day': '1/1/2017', 'temperature':32, 'wind speed':6, 'event':'Rain'},
{'day': '1/2/2017', 'temperature':35, 'wind speed':7, 'event':'Sunny'},
{'day': '1/3/2017', 'temperature':28, 'wind speed':2, 'event':'Snow'}]
df_weatherdata_dict=pd.DataFrame(weather_data_dict)
df_weatherdata_dict